name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

defaults:
  run:
    working-directory: MXCHIP/mxchip_advanced

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        type: [Release]
      # matrix:
      #   os: [ubuntu-latest, windows-latest]
      #   type: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: arm-none-eabi-gcc
      #   uses: ryanwinter/arm-none-eabi-gcc@master
      #   with:
      #     release: '10-2021.10'

      # - name: Install Ninja
      #   uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Checkout iotz
        uses: actions/checkout@v2
        with:
          repository: 'obastemur/iotz'
          path: 'iotz'
          #submodules: recursive
        
      

      # - name: Build binary
      #   run: |
      #     cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" -DCMAKE_BUILD_TYPE="${{ matrix.type }}"
      #     cmake --build build   
      - name: Build binary
        run: |
          ls iotz
          docker info
          # npm i iotz -g
          # iotz update
          # #iotz init
          # iotz --version
      #     cmake --build build   
      

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: '**/*.bin'
